# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("app.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("app.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("app.ico"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("app.ico"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("app.ico"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("app.ico"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("app.ico"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("app.ico"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_H0 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_H0.setGeometry(QtCore.QRect(70, 40, 290, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_H0.setFont(font)
        self.lbl_H0.setObjectName("lbl_H0")
        self.lbl_T = QtWidgets.QLabel(self.centralwidget)
        self.lbl_T.setGeometry(QtCore.QRect(70, 80, 290, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_T.setFont(font)
        self.lbl_T.setObjectName("lbl_T")
        self.lbl_h = QtWidgets.QLabel(self.centralwidget)
        self.lbl_h.setGeometry(QtCore.QRect(70, 120, 290, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_h.setFont(font)
        self.lbl_h.setObjectName("lbl_h")
        self.lbl_alpha0 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_alpha0.setGeometry(QtCore.QRect(70, 160, 290, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_alpha0.setFont(font)
        self.lbl_alpha0.setObjectName("lbl_alpha0")
        self.txt_H0 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_H0.setGeometry(QtCore.QRect(370, 40, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_H0.setFont(font)
        self.txt_H0.setObjectName("txt_H0")
        self.txt_T = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_T.setGeometry(QtCore.QRect(370, 80, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_T.setFont(font)
        self.txt_T.setObjectName("txt_T")
        self.txt_h = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_h.setGeometry(QtCore.QRect(370, 120, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_h.setFont(font)
        self.txt_h.setObjectName("txt_h")
        self.txt_dwApproach = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_dwApproach.setGeometry(QtCore.QRect(370, 160, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_dwApproach.setFont(font)
        self.txt_dwApproach.setObjectName("txt_dwApproach")
        self.btn_calculate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calculate.setGeometry(QtCore.QRect(560, 80, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_calculate.setFont(font)
        self.btn_calculate.setObjectName("btn_calculate")
        self.lbl_L = QtWidgets.QLabel(self.centralwidget)
        self.lbl_L.setGeometry(QtCore.QRect(60, 240, 290, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_L.setFont(font)
        self.lbl_L.setObjectName("lbl_L")
        self.lbl_Cg = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Cg.setGeometry(QtCore.QRect(60, 290, 290, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_Cg.setFont(font)
        self.lbl_Cg.setObjectName("lbl_Cg")
        self.lbl_approachAngle = QtWidgets.QLabel(self.centralwidget)
        self.lbl_approachAngle.setGeometry(QtCore.QRect(60, 340, 290, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_approachAngle.setFont(font)
        self.lbl_approachAngle.setObjectName("lbl_approachAngle")
        self.lbl_refraction = QtWidgets.QLabel(self.centralwidget)
        self.lbl_refraction.setGeometry(QtCore.QRect(60, 440, 290, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_refraction.setFont(font)
        self.lbl_refraction.setObjectName("lbl_refraction")
        self.lbl_shoaling = QtWidgets.QLabel(self.centralwidget)
        self.lbl_shoaling.setGeometry(QtCore.QRect(60, 390, 290, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_shoaling.setFont(font)
        self.lbl_shoaling.setObjectName("lbl_shoaling")
        self.lbl_H = QtWidgets.QLabel(self.centralwidget)
        self.lbl_H.setGeometry(QtCore.QRect(60, 490, 290, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_H.setFont(font)
        self.lbl_H.setObjectName("lbl_H")
        self.lbl_resultL = QtWidgets.QLabel(self.centralwidget)
        self.lbl_resultL.setGeometry(QtCore.QRect(370, 240, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_resultL.setFont(font)
        self.lbl_resultL.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_resultL.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_resultL.setObjectName("lbl_resultL")
        self.lbl_resultCg = QtWidgets.QLabel(self.centralwidget)
        self.lbl_resultCg.setGeometry(QtCore.QRect(370, 290, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_resultCg.setFont(font)
        self.lbl_resultCg.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_resultCg.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_resultCg.setObjectName("lbl_resultCg")
        self.lbl_resultApproach = QtWidgets.QLabel(self.centralwidget)
        self.lbl_resultApproach.setGeometry(QtCore.QRect(370, 340, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_resultApproach.setFont(font)
        self.lbl_resultApproach.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_resultApproach.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_resultApproach.setObjectName("lbl_resultApproach")
        self.lbl_resultShoaling = QtWidgets.QLabel(self.centralwidget)
        self.lbl_resultShoaling.setGeometry(QtCore.QRect(370, 390, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_resultShoaling.setFont(font)
        self.lbl_resultShoaling.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_resultShoaling.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_resultShoaling.setObjectName("lbl_resultShoaling")
        self.lbl_resultRefraction = QtWidgets.QLabel(self.centralwidget)
        self.lbl_resultRefraction.setGeometry(QtCore.QRect(370, 440, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_resultRefraction.setFont(font)
        self.lbl_resultRefraction.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_resultRefraction.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_resultRefraction.setObjectName("lbl_resultRefraction")
        self.lbl_resultHeight = QtWidgets.QLabel(self.centralwidget)
        self.lbl_resultHeight.setGeometry(QtCore.QRect(370, 490, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_resultHeight.setFont(font)
        self.lbl_resultHeight.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_resultHeight.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_resultHeight.setObjectName("lbl_resultHeight")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(590, 480, 131, 51))
        self.label.setObjectName("label")
        self.lbl_datetime = QtWidgets.QLabel(self.centralwidget)
        self.lbl_datetime.setGeometry(QtCore.QRect(590, 540, 191, 21))
        self.lbl_datetime.setObjectName("lbl_datetime")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(560, 160, 131, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Regular Wave Toolbox"))
        self.lbl_H0.setText(_translate("MainWindow", "<html><head/><body><p>Deep water wave height, H<span style=\" vertical-align:sub;\">0</span> (m):</p></body></html>"))
        self.lbl_T.setText(_translate("MainWindow", "<html><head/><body><p>Wave period, T (s):</p></body></html>"))
        self.lbl_h.setText(_translate("MainWindow", "<html><head/><body><p>Water depth, h (m):</p></body></html>"))
        self.lbl_alpha0.setText(_translate("MainWindow", "<html><head/><body><p>Deep water approach angle (in deg.):</p></body></html>"))
        self.btn_calculate.setText(_translate("MainWindow", "Calculate!"))
        self.lbl_L.setText(_translate("MainWindow", "<html><head/><body><p>Wave length, L (m):</p></body></html>"))
        self.lbl_Cg.setText(_translate("MainWindow", "<html><head/><body><p>Group velocity, C<span style=\" vertical-align:sub;\">g</span> (m/s):</p></body></html>"))
        self.lbl_approachAngle.setText(_translate("MainWindow", "<html><head/><body><p>Approach angle (in deg.):</p></body></html>"))
        self.lbl_refraction.setText(_translate("MainWindow", "<html><head/><body><p>Refraction coefficient, K<span style=\" vertical-align:sub;\">r</span>:</p></body></html>"))
        self.lbl_shoaling.setText(_translate("MainWindow", "<html><head/><body><p>Shoaling coefficient, K<span style=\" vertical-align:sub;\">s</span>:</p></body></html>"))
        self.lbl_H.setText(_translate("MainWindow", "<html><head/><body><p>Wave height, H (m):</p></body></html>"))
        self.lbl_resultL.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.lbl_resultCg.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.lbl_resultApproach.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.lbl_resultShoaling.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.lbl_resultRefraction.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.lbl_resultHeight.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Yagiz Arda Cicek, 2020"))
        self.lbl_datetime.setText(_translate("MainWindow", datetime.now().strftime("%Y-%m-%d %H:%M")))
